'use client';
import Link from 'next/link';
import { Edit3, Filter, Plus, Search } from 'lucide-react';
import { Badge } from '@/components/common/Badge';
import { Button } from '@/components/common/Button';
import { Card } from '@/components/common/Card';
import { DataTable } from '@/components/common/DataTable';
import { Input } from '@/components/common/Input';
import { PageHeader } from '@/components/common/PageHeader';
import { LoadingState, EmptyState, ErrorState } from '@/components/common/States';
import { useApiQuery } from '@/hooks/useApiQuery';
import { safeArray, formatDate } from '@/lib/utils';

type Row={id?:string;title?:string;name?:string;topic?:string;email?:string;role?:string;status?:string;level?:number;createdAt?:string;created_at?:string;updatedAt?:string;updated_at?:string};
function statusTone(status?:string){if(status==='PUBLISHED'||status==='ACTIVE'||status==='GRADED'||status==='REVIEWED')return 'success'; if(status==='DRAFT'||status==='PENDING'||status==='CLAIMED')return 'warning'; if(status==='BLOCKED'||status==='ERROR'||status==='ARCHIVED')return 'danger'; return 'default'}
export function ResourceListPage({title,description,query,createHref,detailBase,eyebrow='Management',columns='content'}:{title:string;description?:string;query:()=>Promise<unknown>;createHref?:string;detailBase?:string;eyebrow?:string;columns?:'content'|'users'|'submissions'|'imports'|'comments'}){const {data,loading,error}=useApiQuery(query,[]);const rows=safeArray<Row>((data as any)?.data || data);const cols=columns==='users'?[{header:'Người dùng',cell:(r:Row)=><div><p className="font-semibold">{r.name||r.email}</p><p className="text-xs text-neutralText">{r.email}</p></div>},{header:'Role',cell:(r:Row)=><Badge tone="sage">{r.role||'USER'}</Badge>},{header:'Status',cell:(r:Row)=><Badge tone={statusTone(r.status) as any}>{r.status||'—'}</Badge>},{header:'Ngày tạo',cell:(r:Row)=>formatDate(r.createdAt||r.created_at)},{header:'',cell:(r:Row)=>detailBase&&r.id?<Link href={`${detailBase}/${r.id}`}><Button size="sm" variant="outline"><Edit3 className="h-4 w-4"/> Chi tiết</Button></Link>:null}]:[{header:'Tên nội dung',cell:(r:Row)=><div><p className="font-semibold">{r.title||r.name||r.topic||r.email||r.id}</p><p className="mt-1 font-mono text-[11px] text-neutralText">{r.id}</p></div>},{header:'Level/Role',cell:(r:Row)=>r.level??r.role??'—'},{header:'Status',cell:(r:Row)=><Badge tone={statusTone(r.status) as any}>{r.status||'—'}</Badge>},{header:'Cập nhật',cell:(r:Row)=>formatDate(r.updatedAt||r.updated_at||r.createdAt||r.created_at)},{header:'',cell:(r:Row)=>detailBase&&r.id?<Link href={`${detailBase}/${r.id}`}><Button size="sm" variant="outline"><Edit3 className="h-4 w-4"/> Mở</Button></Link>:null}];return <div><PageHeader eyebrow={eyebrow} title={title} description={description} actions={<>{createHref&&<Link href={createHref}><Button><Plus className="h-4 w-4"/> Tạo mới</Button></Link>}</>}/><Card className="mb-5 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative w-full lg:max-w-sm"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutralText"/><Input className="pl-9" placeholder="Tìm kiếm theo tên, trạng thái, ID..."/></div><div className="flex flex-wrap gap-2"><Button variant="outline"><Filter className="h-4 w-4"/> Bộ lọc</Button><Badge>Table + filter + modal-ready</Badge></div></div></Card>{loading&&<LoadingState/>}{error&&<ErrorState message={error}/>} {!loading&&!error&&rows.length===0&&<EmptyState title="Chưa có dữ liệu" description="Dữ liệu từ backend sẽ hiển thị ở bảng này. Bạn có thể tạo mới hoặc kiểm tra filter/API." action={createHref?<Link href={createHref}><Button>Tạo mới</Button></Link>:undefined}/>} {!loading&&!error&&rows.length>0&&<DataTable data={rows} columns={cols}/>}</div>}
